const $=s=>document.querySelector(s);let root='',workspace='',agentAbort=null,busy=false,providers=[];
async function api(url,opt={}){const r=await fetch(url,opt);if(!r.ok)throw Error((await r.text()).trim()||r.statusText);const ct=r.headers.get('content-type')||'';return ct.includes('json')?r.json():r.text()}
function toast(s){const t=$('#toast');t.textContent=s;t.classList.add('show');clearTimeout(t._x);t._x=setTimeout(()=>t.classList.remove('show'),1800)}
async function boot(){const s=await api('/api/status');root=s.root;workspace=root;$('#workspace').value=root;$('#rootLabel').textContent=root;await loadFiles('');await loadSettings();await agentStatus();setInterval(()=>{if(!document.hidden)loadFiles(workspace,true)},2500)}
async function loadFiles(path='',silent=false){try{const list=await api('/api/files?path='+encodeURIComponent(path));const box=$('#files');box.innerHTML='';for(const f of list){const row=document.createElement('div');row.className='file-row '+(f.dir?'folder':'');row.innerHTML=`<span>${f.dir?'▸':'·'}</span><span></span>`;row.lastChild.textContent=f.name;row.style.paddingLeft=(7+(f.path.split('/').length-1)*12)+'px';row.onclick=()=>f.dir?toggleDir(row,f):openFile(f);box.append(row)}}catch(e){if(!silent)toast(e.message)}}
async function toggleDir(row,f){if(row.dataset.open==='1'){let n=row.nextSibling;while(n&&Number(n.dataset.depth)>Number(row.dataset.depth||0)){const x=n;n=n.nextSibling;x.remove()}row.dataset.open='0';row.firstChild.textContent='▸';return}const depth=Number(row.dataset.depth||0);const list=await api('/api/files?path='+encodeURIComponent(f.path));row.dataset.open='1';row.firstChild.textContent='▾';let after=row;for(const c of list){const x=document.createElement('div');x.className='file-row '+(c.dir?'folder':'');x.dataset.depth=depth+1;x.innerHTML=`<span>${c.dir?'▸':'·'}</span><span></span>`;x.lastChild.textContent=c.name;x.style.paddingLeft=(19+(depth+1)*12)+'px';x.onclick=()=>c.dir?toggleDir(x,c):openFile(c);after.after(x);after=x}}
async function openFile(f){try{$('#preview').textContent=await api('/api/file?path='+encodeURIComponent(f.path));$('#fileLabel').textContent=f.path}catch(e){toast(e.message)}}
async function loadSettings(){const s=await api('/api/settings');providers=s.providers;const sel=$('#provider');sel.innerHTML='';for(const p of providers){const o=document.createElement('option');o.value=p.id;o.textContent=p.label+(p.configured?' · configured':'');sel.append(o)}sel.value=s.activeProvider||'opencode';updateProviderUI()}
function updateProviderUI(){const p=providers.find(x=>x.id===$('#provider').value);$('#apiKey').value='';$('#apiKey').placeholder=p?.configured?'Configured · enter a new key to replace':p?.hint||'API key';$('#providerNote').textContent=$('#provider').value==='opencode'?'Cortex v0.1 runs the coding agent through OpenCode Zen with DeepSeek V4 Flash. Other provider credentials can be stored now; model/provider selection follows.': 'Credential storage is ready. Cortex v0.1 agent execution currently uses OpenCode Zen.'}
async function saveKey(remove=false){const provider=$('#provider').value,key=remove?'':$('#apiKey').value.trim();if(!remove&&!key&&providers.find(x=>x.id===provider)?.configured){toast('Existing key kept');return}await api('/api/settings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({provider,key})});await loadSettings();await agentStatus();toast(remove?'Key removed':'Provider saved')}
async function agentStatus(){try{const s=await api('/api/agent/status');$('#dot').classList.toggle('ready',s.available);$('#agentState').textContent=!s.opencodeInstalled?'OpenCode not installed':!s.credentialAvailable?'API key required':s.provider!=='opencode'?'Select OpenCode Zen':'Ready'}catch(e){$('#agentState').textContent=e.message}}
function clipped(v,n=2600){const s=String(v??'').trim();return s.length>n?s.slice(0,n)+'\n…':s}
function toolText(raw){const p=raw.part||raw,st=p.state||{},tool=p.tool||raw.tool||raw.name||'tool',status=st.status||'';const input=st.input||p.input||{},lines=[`↳ ${tool}${status?' · '+status:''}`];if(tool==='bash'&&input.command)lines.push('$ '+input.command);else if(input.filePath||input.path)lines.push(input.filePath||input.path);if(st.error)lines.push('ERROR: '+clipped(typeof st.error==='string'?st.error:JSON.stringify(st.error)));else if(st.output)lines.push(clipped(st.output));return lines.join('\n')}
function summarize(ev){const raw=ev?.data?.data||ev?.data||{},type=String(raw.type||'');if(ev.type==='error')return raw.message||'Agent failed';if(ev.type==='recovered')return raw.text||'';if(ev.type==='done')return `Done · ${raw.inputTokens||0} input · ${raw.outputTokens||0} output tokens`;if(ev.type==='output')return raw.text||'';if(type.includes('tool'))return toolText(raw);return raw.part?.text||raw.text||''}
function renderTool(row,text){const lines=text.split('\n'),m=lines[0].match(/^↳ ([\w.:-]+) · (completed|error|running|pending)$/);if(!m){row.textContent=text;return}const h=document.createElement('div');h.className='tool-head';h.innerHTML='<span class="tool-arrow">↳ </span><span class="tool-name"></span><span> · </span><span class="tool-status"></span>';h.querySelector('.tool-name').textContent=m[1];const st=h.querySelector('.tool-status');st.textContent=m[2];st.classList.add(m[2]);row.append(h);if(lines.length>1){const b=document.createElement('div');b.className='tool-body';b.textContent=lines.slice(1).join('\n');row.append(b)}}
function feed(kind,text){const clean=String(text??'').trim();if(!clean)return;$('#feed .empty')?.remove();const row=document.createElement('div');row.className='event '+kind;row.dataset.kind=kind;if(kind==='tool')renderTool(row,clean);else row.textContent=clean;$('#feed').append(row);$('#feed').scrollTop=$('#feed').scrollHeight}
async function runAgent(prompt){if(busy)return;busy=true;$('#run').disabled=true;$('#prompt').disabled=true;$('#stop').hidden=false;$('#activity').hidden=false;agentAbort=new AbortController();feed('user',prompt);try{const r=await fetch('/api/agent/run',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({workspace,prompt}),signal:agentAbort.signal});if(!r.ok)throw Error((await r.text()).trim()||r.statusText);const rd=r.body.getReader(),dec=new TextDecoder();let buf='';for(;;){const {value,done}=await rd.read();if(done)break;buf+=dec.decode(value,{stream:true});let i;while((i=buf.indexOf('\n'))>=0){const line=buf.slice(0,i).trim();buf=buf.slice(i+1);if(!line)continue;const ev=JSON.parse(line),text=summarize(ev);if(text){const raw=ev?.data?.data||ev?.data||{},t=String(raw.type||'');feed(ev.type==='error'?'error':ev.type==='done'?'done':t.includes('tool')?'tool':'assistant',text)}}}await loadFiles('',true)}catch(e){feed('error',e.name==='AbortError'?'Agent stopped.':e.message)}finally{busy=false;agentAbort=null;$('#run').disabled=false;$('#prompt').disabled=false;$('#stop').hidden=true;$('#activity').hidden=true;agentStatus()}}
$('#agentForm').onsubmit=e=>{e.preventDefault();const p=$('#prompt').value.trim();if(!p)return;$('#prompt').value='';runAgent(p)};$('#prompt').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();$('#agentForm').requestSubmit()}};$('#stop').onclick=()=>agentAbort?.abort();$('#copy').onclick=async()=>{const labels={user:'You',assistant:'Agent',tool:'Tool',error:'Error',done:'Status'},text=[...document.querySelectorAll('.event')].map(x=>`${labels[x.dataset.kind]||'Agent'}:\n${x.innerText.trim()}`).join('\n\n');if(!text)return toast('Nothing to copy');await navigator.clipboard.writeText(text);toast('Session copied')};$('#settingsBtn').onclick=()=>{$('#modal').hidden=false;loadSettings()};$('#closeSettings').onclick=()=>$('#modal').hidden=true;$('#modal').onclick=e=>{if(e.target===$('#modal'))$('#modal').hidden=true};$('#provider').onchange=updateProviderUI;$('#saveKey').onclick=()=>saveKey(false);$('#deleteKey').onclick=()=>saveKey(true);$('#open').onclick=async()=>{workspace=$('#workspace').value.trim()||root;try{await loadFiles(workspace);$('#rootLabel').textContent=workspace;toast('Workspace opened')}catch(e){toast(e.message)}};$('#refresh').onclick=()=>loadFiles();boot().catch(e=>toast(e.message));
